#brew services restart postgresql@17
#redis-server

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: admin
    password: admin
    url: jdbc:postgresql://localhost:5432/postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379


email-verification:
  required: true

mail:
  config:
    password: yeianguniwrqwcnk
    username: bkeldiyarov@yandex.ru
    host: smtp.yandex.ru
springdoc:
  api-docs:
    enabled: true
    path: /api-docs
auth:
  refresh-token-ttl: 864000000
  
